solved stam exercise
osherdp/python-training pull request #61
Opened 2020-03-24 16:42 UTC by kerenGuez

2020-03-24 16:50 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +__author__ = "Keren"
No need

2020-03-24 16:50 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +__author__ = "Keren"
The first line in the file should be a description of the purpose of the file

2020-03-24 16:50 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +    """
The first line of docs should be a description of the function \ class , etc

2020-03-24 16:50 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +        line: (str) a line of text
the type should be before the ":"

2020-03-24 16:50 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +    """
look at chapter 3.8 how the docs should look like
https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings

2020-03-24 16:50 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +    """ The function gets file path, edits it and saves the new edited file to a new location
look at pep8 conventions (how many chars per line, space line after logic block, etc.)
https://realpython.com/python-pep8/#blank-lines

2020-03-24 16:50 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +    try:
you can instead check if file exists at the start

2020-03-24 16:50 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +            new_path_to_save = r"C:\Users\keren\Desktop\newfile.txt"
you should put the output path as function argument

2020-03-24 16:50 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +                    print("line "+line, end="")
no need

2020-03-25 10:29 UTC, rfire01 requested changes

2020-03-25 10:29 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +LAST_NAME = "Guez"
imports and the code should be separated with blank lines

2020-03-25 10:29 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +    """This function concatenates a line with some given text
dot at end of sentence (in all docs)

2020-03-25 10:29 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +
remove

2020-03-25 10:29 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +    """This function concatenates a line with some given text
functions doc should start with Imperative verb.
For example: Concatenate a line with...
Add something with
etc.

2020-03-25 10:29 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +    if os.path.exists(filename) and os.path.exists(output_file[:last_slash]):
you don't need to check if output file exists, as you are creating it now

2020-03-25 10:29 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +        print(f"either the original file path or the output path don't exist")
error messages should be informative.
Don't let the user guess what the problem, say exactly, is it the orignal or output?

2020-03-25 10:29 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +                                    for line in file)
this doesn't look good, try to think on a better way

2020-03-25 21:04 UTC, rfire01 requested changes

2020-03-25 21:04 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +        output_folder (str) : The path to the output folder.
blank line between args and returns

2020-03-25 21:04 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +    """Checks if paths are valid and prints a message accordingly.
Like I said imperative verbs (Check not checks), in both functions

2020-03-25 21:04 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +        False : If any path isn't valid.
in returns you write the type of the returned value and what it represents, not its values

2020-03-25 21:04 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +    return True
pep8

2020-03-25 21:04 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +    if check_exists(filename, output_dir):
instead of putting all the logic under if, you can first check it, if its not exists exits the function, and if not do the logic

2020-03-26 12:13 UTC, osherdp requested changes
It's a very elegant solution, just a few fixes are needed

2020-03-26 12:13 UTC, osherdp commented on basic/stam/StamExAnswer.py
> +    if not os.path.exists(input_file):
the `exists` usage is redundant
If one of the files doesn't exist it will raise an exception nevertheless

2020-03-26 12:13 UTC, osherdp commented on basic/stam/StamExAnswer.py
> +            new_concat_lines = (FIRST_NAME + line[:-1] + LAST_NAME + "\n"
move into the `for` below. For example:
```
for line in file:
    new_file.write(FIRST_NAME + line[:-1] + ...)
```

2020-03-26 12:13 UTC, osherdp commented on basic/stam/StamExAnswer.py
> +            new_concat_lines = (FIRST_NAME + line[:-1] + LAST_NAME + "\n"
don't use string concatenation, use f-strings

2020-03-27 08:05 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +LAST_NAME = "Guez"
reorder by length

2020-03-27 08:08 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +        print(e)
The try except here are pointless.
At the moment, you catch the exception and just print it as it is and ending the program. If this the case, you can just remove the try except, and let it throw exception if it fails.
If you do want to use try except here, you should do something different, such as printing your own error message

2020-03-27 08:08 UTC, rfire01 commented on basic/stam/StamExAnswer.py
> +        stam(path, new_path_to_save)
blank line after logic block

2020-03-27 14:27 UTC, osherdp requested changes

2020-03-27 14:27 UTC, osherdp commented on basic/stam/StamExAnswer.py
> +"""Reads a file, edits it and saves it in a new location."""
Please make sure you name all python files like so:
* No capital letters, only small letters, underscores and (rarely) numbers
* Most meaningful name possible. In this training, you can remove usage of words like "exercise" and "answer", as it's not the essence of the code written
* Short as possible, but not too short if readability will suffer from it

2020-03-29 15:11 UTC, rfire01 requested changes

2020-03-29 15:11 UTC, rfire01 commented on basic/stam/stam.py
> +INPUT_FILE = 1
reorder

2020-03-29 15:11 UTC, rfire01 commented on basic/stam/stam.py
> +        print(f"The path '{e.filename}' was not found")
pep8

2020-03-29 15:11 UTC, rfire01 commented on basic/stam/stam.py
> +        print(e)
It is ok for your code to throw an exception.
If you just catch it and print it to the screen it doesn't give additional information.

2020-03-29 15:11 UTC, rfire01 commented on basic/stam/stam.py
> +    main()
blank line at the end of file (pep8)

2020-03-29 20:56 UTC, rfire01 commented on basic/stam/stam.py
> +    main()
?

2020-03-30 07:49 UTC, closed without merging